local M = {}

function M.build(p)
  local groups = {
    Normal = { fg = p.fg_main, bg = p.bg_main },
    NormalNC = { fg = p.fg_main, bg = p.bg_main },
    Cursor = { fg = p.bg_main, bg = p.cursor },
    CursorLine = { bg = p.bg_accent },
    CursorColumn = { bg = p.bg_shadow_subtle },
    ColorColumn = { bg = p.bg_shadow_subtle },
    CursorLineFold = { bg = p.bg_accent },
    CursorLineSign = { bg = p.bg_main },
    LineNr = { fg = p.fg_shadow_subtle },
    CursorLineNr = { fg = p.fg_main, bold = true },
    SignColumn = { fg = p.fg_shadow_subtle, bg = p.bg_main },
    FoldColumn = { fg = p.fg_shadow_subtle, bg = p.bg_main },
    EndOfBuffer = { fg = p.bg_main },
    VertSplit = { fg = p.border },
    WinSeparator = { fg = p.border },
    StatusLine = { fg = p.fg_accent, bg = p.bg_shadow_intense },
    StatusLineNC = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    StatusLineTerm = { link = "StatusLine " },
    StatusLineTermNC = { link = "StatusLineNC" },
    TabLine = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    TabLineSel = { fg = p.fg_main, bg = p.bg_main, bold = true },
    TabLineFill = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    Pmenu = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    PmenuMatch = { fg = p.fg_shadow_subtle, underline = true },
    PmenuMatchSel = { fg = p.fg_shadow_subtle, underline = true },
    PmenuSel = { fg = p.fg_accent, bg = p.bg_shadow_intense },
    PmenuSbar = { bg = p.bg_shadow_subtle },
    PmenuThumb = { bg = p.bg_shadow_intense },
    PmenuKind = { link = "Pmenu" },
    PmenuKindSel = { link = "PmenuSel" },
    PmenuExtra = { link = "Pmenu" },
    PmenuExtraSel = { link = "PmenuSel" },
    Visual = { fg = p.fg_accent, bg = p.bg_shadow_intense },
    Search = { fg = p.fg_main, bg = p.bg_shadow_intense },
    IncSearch = { fg = p.bg_main, bg = p.fg_shadow_intense },
    MatchParen = { fg = p.fg_shadow_intense, bg = p.bg_shadow_intense },
    Folded = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    Title = { fg = p.fg_shadow_intense, bold = true },
    Directory = { fg = p.fg_accent },
    NonText = { fg = p.fg_shadow_subtle },
    Whitespace = { fg = p.fg_shadow_subtle },
    SpecialKey = { fg = p.fg_shadow_subtle },
    ModeMsg = { fg = p.fg_shadow_intense, bold = true },
    MoreMsg = { fg = p.fg_shadow_intense, bold = true },
    WarningMsg = { fg = p.fg_yellow, bold = true },
    ErrorMsg = { fg = p.fg_red, bold = true },
    Question = { fg = p.fg_shadow_intense, bold = true },
    WildMenu = { fg = p.fg_main, bg = p.bg_accent },
    QuickFixLine = { fg = p.fg_main, bg = p.bg_accent, bold = true },
    WinBar = { fg = p.fg_shadow_subtle, bg = p.bg_main },
    WinBarNC = { fg = p.fg_shadow_subtle, bg = p.bg_main },
    DiffAdded = { fg = p.fg_green },
    DiffRemoved = { fg = p.fg_red },
    DiffChanged = { fg = p.fg_yellow },
    DiffFile = { fg = p.fg_shadow_intense, bold = true },
    DiffNewFile = { fg = p.fg_shadow_intense, bold = true },
    DiffLine = { fg = p.fg_shadow_subtle },
    SpellBad = { undercurl = true, sp = p.fg_red },
    SpellCap = { undercurl = true, sp = p.fg_blue },
    SpellLocal = { undercurl = true, sp = p.fg_cyan },
    SpellRare = { undercurl = true, sp = p.fg_magenta },

    Comment = { fg = p.fg_accent, italic = true },
    Constant = { fg = p.fg_main },
    String = { fg = p.fg_shadow_subtle },
    Character = { fg = p.fg_shadow_subtle },
    Number = { fg = p.fg_main },
    Boolean = { fg = p.fg_main },
    Float = { fg = p.fg_main },
    Identifier = { fg = p.fg_main, italic = true },
    Function = { fg = p.fg_shadow_intense },
    Statement = { fg = p.fg_shadow_intense, bold = true },
    Conditional = { fg = p.fg_shadow_intense, bold = true },
    Repeat = { fg = p.fg_shadow_intense, bold = true },
    Label = { fg = p.fg_shadow_intense, bold = true },
    Operator = { fg = p.fg_shadow_intense, bold = true },
    Keyword = { fg = p.fg_shadow_intense, bold = true },
    Exception = { fg = p.fg_shadow_intense, bold = true },
    PreProc = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Include = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Define = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Macro = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    PreCondit = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Type = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    StorageClass = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Structure = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Typedef = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    Special = { fg = p.fg_main },
    SpecialChar = { fg = p.fg_shadow_subtle },
    Tag = { fg = p.fg_shadow_subtle },
    Delimiter = { fg = p.fg_main },
    SpecialComment = { fg = p.fg_shadow_subtle, italic = true },
    Debug = { fg = p.fg_shadow_subtle },
    Underlined = { fg = p.fg_accent, underline = true },
    Ignore = { fg = p.fg_shadow_subtle },
    Error = { fg = p.fg_red, bold = true },
    Todo = { fg = p.fg_yellow, bold = true },

    DiffAdd = { fg = p.fg_neutral, bg = p.bg_green },
    DiffChange = { fg = p.fg_neutral, bg = p.bg_yellow },
    DiffDelete = { fg = p.fg_neutral, bg = p.bg_red },
    DiffText = { fg = p.fg_main, bg = p.bg_shadow_intense, bold = true },

    DiagnosticError = { fg = p.fg_red, bold = true },
    DiagnosticWarn = { fg = p.fg_yellow, bold = true },
    DiagnosticInfo = { fg = p.fg_cyan, bold = true },
    DiagnosticHint = { fg = p.fg_green, bold = true },
    DiagnosticVirtualTextError = { fg = p.fg_red, bg = p.bg_red },
    DiagnosticVirtualTextWarn = { fg = p.fg_yellow, bg = p.bg_yellow },
    DiagnosticVirtualTextInfo = { fg = p.fg_cyan, bg = p.bg_cyan },
    DiagnosticVirtualTextHint = { fg = p.fg_green, bg = p.bg_green },
    DiagnosticSignError = { fg = p.fg_red, bg = p.bg_main },
    DiagnosticSignWarn = { fg = p.fg_yellow, bg = p.bg_main },
    DiagnosticSignInfo = { fg = p.fg_cyan, bg = p.bg_main },
    DiagnosticSignHint = { fg = p.fg_green, bg = p.bg_main },
    DiagnosticUnderlineError = { undercurl = true, sp = p.fg_red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = p.fg_yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = p.fg_cyan },
    DiagnosticUnderlineHint = { undercurl = true, sp = p.fg_green },
    DiagnosticFloatingError = { fg = p.fg_red },
    DiagnosticFloatingWarn = { fg = p.fg_yellow },
    DiagnosticFloatingInfo = { fg = p.fg_cyan },
    DiagnosticFloatingHint = { fg = p.fg_green },

    LspReferenceText = { bg = p.bg_accent, underline = false, bold = true },
    LspReferenceRead = { bg = p.bg_accent, underline = true },
    LspReferenceWrite = { bg = p.bg_accent, underline = true },
    LspInlayHint = { fg = p.fg_shadow_subtle, bg = p.bg_accent, underline = true },
    LspSignatureActiveParameter = { fg = p.fg_shadow_intense, bg = p.bg_accent, bold = true, underline = true },

    GitSignsAdd = { fg = p.fg_green },
    GitSignsChange = { fg = p.fg_yellow },
    GitSignsDelete = { fg = p.fg_red },
    GitSignsAddNr = { fg = p.fg_green },
    GitSignsChangeNr = { fg = p.fg_yellow },
    GitSignsDeleteNr = { fg = p.fg_red },
    GitSignsAddLn = { bg = p.bg_green },
    GitSignsChangeLn = { bg = p.bg_yellow },
    GitSignsDeleteLn = { bg = p.bg_red },

    CmpItemAbbr = { fg = p.fg_main },
    CmpItemAbbrMatch = { fg = p.fg_shadow_intense, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.fg_shadow_intense, bold = true },
    CmpItemMenu = { fg = p.fg_shadow_subtle },
    CmpItemKind = { fg = p.fg_shadow_subtle },

    BlinkCmpLabel = { fg = p.fg_main },
    BlinkCmpLabelMatch = { fg = p.fg_shadow_intense, bold = true },
    BlinkCmpLabelDetail = { fg = p.fg_shadow_subtle },
    BlinkCmpMenu = { fg = p.fg_shadow_subtle },
    BlinkCmpKind = { fg = p.fg_shadow_subtle },
    BlinkCmpSource = { fg = p.fg_shadow_subtle },
    BlinkCmpGhostText = { fg = p.fg_shadow_subtle, italic = true },

    TelescopeBorder = { fg = p.border, bg = p.bg_main },
    TelescopeNormal = { fg = p.fg_main, bg = p.bg_main },
    TelescopeSelection = { fg = p.fg_main, bg = p.bg_accent },
    TelescopeSelectionCaret = { fg = p.fg_shadow_intense, bg = p.bg_accent, bold = true },
    TelescopePromptBorder = { fg = p.border, bg = p.bg_shadow_subtle },
    TelescopePromptNormal = { fg = p.fg_main, bg = p.bg_shadow_subtle },
    TelescopePromptTitle = { fg = p.fg_shadow_intense, bg = p.bg_shadow_subtle, bold = true },
    TelescopeResultsTitle = { fg = p.fg_shadow_intense, bg = p.bg_main, bold = true },
    TelescopePreviewTitle = { fg = p.fg_shadow_intense, bg = p.bg_main, bold = true },
    TelescopeMatching = { fg = p.fg_shadow_intense, bold = true },
    TelescopePromptCounter = { fg = p.fg_shadow_subtle },

    FzfLuaNormal = { fg = p.fg_main, bg = p.bg_main },
    FzfLuaBorder = { fg = p.border, bg = p.bg_main },
    FzfLuaTitle = { fg = p.fg_shadow_intense, bg = p.bg_main, bold = true },
    FzfLuaPrompt = { fg = p.fg_shadow_subtle, bg = p.bg_shadow_subtle },
    FzfLuaCursor = { fg = p.fg_main, bg = p.bg_accent },
    FzfLuaCursorLine = { bg = p.bg_accent },
    FzfLuaHeader = { fg = p.fg_shadow_subtle },
    FzfLuaPath = { fg = p.fg_shadow_subtle },
    FzfLuaLiveSym = { fg = p.fg_shadow_intense },
    FzfLuaFzfPointer = { fg = p.fg_shadow_intense, bold = true },

    WhichKey = { fg = p.fg_shadow_intense, bold = true },
    WhichKeyGroup = { fg = p.fg_shadow_subtle },
    WhichKeyDesc = { fg = p.fg_main },
    WhichKeySeparator = { fg = p.fg_shadow_subtle },
    WhichKeyFloat = { fg = p.fg_main, bg = p.bg_shadow_subtle },
    WhichKeyValue = { fg = p.fg_shadow_subtle },

    NvimTreeNormal = { fg = p.fg_main, bg = p.bg_main },
    NvimTreeNormalNC = { fg = p.fg_main, bg = p.bg_main },
    NvimTreeRootFolder = { fg = p.fg_shadow_intense, bold = true },
    NvimTreeFolderName = { fg = p.fg_shadow_subtle },
    NvimTreeOpenedFolderName = { fg = p.fg_shadow_intense, bold = true },
    NvimTreeEmptyFolderName = { fg = p.fg_shadow_subtle },
    NvimTreeIndentMarker = { fg = p.fg_shadow_subtle },
    NvimTreeWinSeparator = { fg = p.border },
    NvimTreeGitDirty = { fg = p.fg_yellow },
    NvimTreeGitNew = { fg = p.fg_green },
    NvimTreeGitDeleted = { fg = p.fg_red },
    NvimTreeSpecialFile = { fg = p.fg_shadow_intense, bold = true },
    NvimTreeImageFile = { fg = p.fg_shadow_subtle },
    NvimTreeSymlink = { fg = p.fg_shadow_intense },

    ["@comment"] = { fg = p.fg_accent, italic = true },
    ["@string"] = { fg = p.fg_shadow_subtle },
    ["@number"] = { fg = p.fg_main },
    ["@boolean"] = { fg = p.fg_main },
    ["@function"] = { fg = p.fg_shadow_intense },
    ["@function.builtin"] = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    ["@keyword"] = { fg = p.fg_shadow_intense, bold = true },
    ["@keyword.return"] = { fg = p.fg_shadow_intense, bold = true },
    ["@keyword.import"] = { fg = p.fg_shadow_intense, bold = true },
    ["@keyword.directive"] = { fg = p.fg_shadow_intense, bold = true },
    ["@keyword.directive.define"] = { fg = p.fg_shadow_intense, bold = true },
    ["@type"] = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    ["@type.builtin"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@type.definition"] = { fg = p.fg_shadow_subtle, bold = true, italic = true },
    ["@variable"] = { fg = p.fg_main },
    ["@variable.builtin"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@variable.parameter"] = { fg = p.fg_main, italic = true },
    ["@variable.member"] = { fg = p.fg_shadow_subtle },
    ["@constant"] = { fg = p.fg_main },
    ["@constant.builtin"] = { fg = p.fg_shadow_subtle },
    ["@constant.macro"] = { fg = p.fg_shadow_subtle },
    ["@punctuation.delimiter"] = { fg = p.fg_main },
    ["@punctuation.bracket"] = { fg = p.fg_main },
    ["@operator"] = { fg = p.fg_shadow_intense, bold = true },
    ["@module"] = { fg = p.fg_shadow_subtle },
    ["@tag"] = { fg = p.fg_shadow_subtle },
    ["@tag.attribute"] = { fg = p.fg_shadow_subtle },
    ["@tag.delimiter"] = { fg = p.fg_shadow_subtle },
    ["@property"] = { fg = p.fg_shadow_subtle },
    ["@field"] = { fg = p.fg_shadow_subtle },
    ["@constructor"] = { fg = p.fg_shadow_subtle },
    ["@label"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@conditional"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@repeat"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@exception"] = { fg = p.fg_shadow_subtle, bold = true },
    ["@markup.heading"] = { fg = p.fg_shadow_intense, bold = true },
    ["@markup.italic"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@markup.bold"] = { fg = p.fg_shadow_intense, bold = true },
    ["@markup.strikethrough"] = { fg = p.fg_shadow_subtle, strikethrough = true },
    ["@markup.underline"] = { fg = p.fg_accent, underline = true },
    ["@markup.link"] = { fg = p.fg_accent, underline = true },
    ["@markup.list"] = { fg = p.fg_shadow_subtle },
    ["@markup.raw"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@markup.quote"] = { fg = p.fg_shadow_subtle, italic = true },
    ["@diff.plus"] = { fg = p.fg_green },
    ["@diff.minus"] = { fg = p.fg_red },
    ["@diff.delta"] = { fg = p.fg_yellow },
    ["@comment.todo"] = { fg = p.fg_yellow, bold = true },
  }

  return groups
end

return M
